myproject/sesac/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

myproject/sesac/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
import random

@main.route('/')
def index():
    return redirect(url_for('main_views.grid'))

# @main.route('/join', methods=['GET', 'POST'])
# def join_chat():
#     """Login form to enter a room."""
#     form = LoginForm()
#     if form.validate_on_submit():
#         session['name'] = form.name.data
#         session['room'] = form.room.data
#         return redirect(url_for('.chat'))
#     elif request.method == 'GET':
#         form.name.data = session.get('name', '')
#         form.room.data = session.get('room', '')
#     return render_template('index.html', form=form)


@main.route('/chat/<tag>')
def chat(tag='All'):
    """Chat room. The user's name and room must be stored in
    the session."""
    try:
        session['name'] = session['userSubNm']
    except:
        r = random.randrange(1, 1000)
        session['name'] = 'SESAC_' + str(r).zfill(3)
    session['room'] = str(tag)
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('pages/chat.html', name=name, room=room)

myproject/sesac/views/board_views.py
# myproject/sesac/views/board_views.py
from flask import Flask, url_for, request, session, redirect, app
from flask import Blueprint, render_template
from ..sqlModule import DBUpdater
bp = Blueprint('board_views', __name__, url_prefix='/board')

# /board
@bp.route('/')
def board():
    print("board()")
    db = DBUpdater()
    
    number= 5
    page = request.args.get('page', type=int, default=1)
    paging = db.pageSelect2(number ,page)
    board_list = db.load_board_list()
    board_ls = db.load_board_list()
    post_list = db.load_post_list()
    post_len= len(post_list)
    post_len2={'count' : len(post_list)}
    ## 최대 페이지 = 전체 게시글수 -1 을 10으로 나눈 몫에 +1
    max_page = (post_len-1) // number +1
    boards={}
    boards['number']= number
    boards['page']= page
    boards['board_list'] = board_list
    boards['postCnt']= post_len2
    boards['post_list']= paging
    boards['max_page']= list(range(1, max_page+1))

    print(boards)
    # 전체 게시판 html 불러오기
    return render_template('pages/board.html', boards=boards, board_ls=board_ls)

# /board/boardId
@bp.route('/brdId=<int:brdId>/', methods=('GET', 'POST'))
def board_boardID(brdId):
    number= 5
    page = request.args.get('page', type=int, default=1)
    """
    Args:
        brdId (int): 게시판 ID
    """
    print('board_boardID(brdId) -', brdId,"\n")
    
    db = DBUpdater()
    # board_list = 전체 게시판 리스트
    board_list = db.load_board_list()
    # data = 특정 게시판의 게시물 리스트
    data = db.eachPageSelect2(number, page, brdId)
    ## 특정 게시판의 카운트수
    cntAll= db.pageCnt(brdId)
    max_page = (cntAll['count'] -1) // number +1
    boards={}
    boards['number']= number
    boards['page']= page
    boards['brdId']= brdId
    boards['board_list']= board_list
    boards['post_list'] = data
    boards['postCnt']= cntAll
    boards['max_page']= list(range(1, max_page+1))
    print('-'*20,boards)
    return render_template('pages/board.html', boards=boards, board_ls=board_list)

@bp.route('/comp/')
def compInfo():
    db = DBUpdater()
    board_ls = db.load_board_list()
    return render_template('pages/competition.html', board_ls=board_ls)

myproject/sesac/views/comment_views.py
# myproject/sesac/views/post_views.py
from flask import Flask, url_for, request, session, redirect, app, flash
from flask import Blueprint, render_template
from ..sqlModule import DBUpdater
from datetime import datetime

bp = Blueprint('comment_views', __name__, url_prefix='/comment')

db = DBUpdater()
board_ls = db.load_board_list()

# 댓글 추가
@bp.route('/add/<int:pstId>/', methods=('GET', 'POST'))
def comment_add(pstId):
    print('comment_add(pstId) -', pstId)
    
    # session이 있을 경우
    if session :
        userId = session['userId']
        if request.form['cmtCntnt'].strip() == "":
            return redirect(url_for('post_views.post', pstId=pstId))
        cmtCntnt = request.form['cmtCntnt']

        # 특정 게시물 html 불러오기
        db = DBUpdater()
        db.insert_comment(pstId , userId, cmtCntnt)
        return redirect(url_for('post_views.post', pstId=pstId, board_ls=board_ls))
    
    return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기 </a>"



# 댓글 삭제
@bp.route('/del/<int:cmtId>/', methods=('GET', 'POST'))
def comment_del(cmtId):
    print('comment_del(cmtId) -', cmtId)
    db = DBUpdater()
    data = db.match_cmtId(cmtId)
    
    # session이 있을 경우
    if session :
		# 세션에 있는 'username' 값과 특정 게시물의 작성자 ID가 같은지 확인
        if str(session['username']) == str(data[0]['userId']):
            # 댓글 삭제
            db.del_comm(cmtId)

        else:
            print('id가 다름')
            flash('삭제 권한이 없습니다.')
            # 특정 게시물 html 불러오기
        return redirect(url_for('post_views.post', pstId=data[0]['pstId'], board_ls=board_ls))
    
    return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기 </a>"

myproject/sesac/views/main_views.py
# myproject/sesac/views/post_views.py
from flask import Flask, url_for, request, session, redirect, app, jsonify
from flask import Blueprint, render_template
from ..sqlModule import DBUpdater
from datetime import datetime

bp = Blueprint('main_views', __name__, url_prefix='/main')

# /post/pstId=<int:pstId>
# 특정 게시물로 이동
@bp.route('/')
def grid():

    db = DBUpdater()
    board_ls = db.load_board_list()
    
    post_dict = {}
    for board in board_ls:
        brdId = board['brdId']
        post_dict[brdId] = db.load_post_brdId_list2(brdId)[:5]
        print(post_dict)
        print('\n\n\n')
    # 특정 게시물 html 불러오기
    return render_template('pages/main.html', board_ls=board_ls, post_dict=post_dict)



# 게시물 클릭하면 조회수 올리기
@bp.route('/vw', methods=('GET', 'POST'))
def vwFunc():
    # method = POST
    if(request.method == 'POST'):
        # main.html에서 받아온 pstId 저장
        pstId = request.get_json()["pstId"]
        
        # 조회수 +1 한 후 저장

        db = DBUpdater()
        vwCnt = db.extractWhere("vwCnt", "Post", "pstId", int(pstId))
        vwCnt = int(vwCnt)+1
        db.addVwCnt(vwCnt, pstId)
        
        # pstId return
        return jsonify({'msg': pstId})
    
    # method = GET
    else:
        render_template('pages/main.html')

myproject/sesac/views/post_views.py
# myproject/sesac/views/post_views.py
from flask import Flask, url_for, request, session, redirect, app, flash
from flask import Blueprint, render_template
from ..sqlModule import DBUpdater
from datetime import datetime

bp = Blueprint('post_views', __name__, url_prefix='/post')

db = DBUpdater()
board_ls = db.load_board_list()


# /post/pstId=<int:pstId>
# 특정 게시물로 이동
@bp.route('/pstId=<int:pstId>')
def post(pstId):
	"""
	Args:
		pstId (int): 게시물 ID
	"""
	print('post(pstId) ------', pstId)

    # data = 특정 게시물 ID 필터링
	db = DBUpdater()
	data = db.load_post_pstId_list(pstId)
	userSN = db.load_userInfo_userId_list(data[0]['userId'])
	print(userSN)	
	comment_list = db.load_comm_pstId_list(pstId)
	board_ls = db.load_board_list()

	# 특정 게시물 html 불러오기
	return render_template('pages/post.html', post_list=data, comment_list=comment_list, board_ls=board_ls, userSN=userSN)


# /post/del/pstId=<int:pstId>
# 특정 게시물 편집하기
@bp.route('/del/pstId=<int:pstId>', methods=('GET', 'POST'))
def post_del(pstId):
	print('post_del(pstId) -', pstId)

    # data = 특정 게시물 ID 필터링
	db = DBUpdater()
	data = db.load_post_pstId_list(pstId)
	board_ls = db.load_board_list()
	print(data)
    # session의 'username'이 있으면 로그인
	if "username" in session:
		# 세션이 있는 경우
		# 세션에 있는 'username' 값과 특정 게시물의 작성자 ID가 같은지 확인
		if str(session['username']) == str(data[0]['userId']):
			
			db.del_post(pstId)
			# 특정 게시물 편집 html 불러오기
			return redirect(url_for('board_views.board'), board_ls=board_ls)

		else:
			print('id가 다름')
			flash("삭제 권한이 없습니다.")
			# 특정 게시물 html 불러오기
			return redirect(url_for('post_views.post', pstId=pstId, board_ls=board_ls))
	else:
		# 세션이 없는 경우
		print('First Login')
		return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기! </a>"


# /post/edit/pstId=<int:pstId>
# 특정 게시물 편집하기
@bp.route('/edit/pstId=<int:pstId>', methods=('GET', 'POST'))
def post_edit(pstId):
    
	print('post_edit(pstId) -', pstId)
    
    # data = 특정 게시물 ID 필터링
	db = DBUpdater()
	data = db.load_post_pstId_list(pstId)
	board_ls = db.load_board_list()
    # session의 'username'이 있으면 로그인
	if "username" in session:
		# 세션이 있는 경우
		# 세션에 있는 'username' 값과 특정 게시물의 작성자 ID가 같은지 확인
		if str(session['username']) == str(data[0]['userId']):
			# 특정 게시물 편집 html 불러오기
			return render_template('pages/post.edit.html', post_list=data, board_ls=board_ls)

		else:
			print('id가 다름')
			flash("수정 권한이 없습니다.")
			# 특정 게시물 html 불러오기
			return redirect(url_for('post_views.post', pstId=pstId))
	else:
		# 세션이 없는 경우
		print('First Login')
		return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기! </a>"


# /post/write
# 작성하기 버튼 클릭
# 게시물 새로 작성하기
@bp.route('/write/<int:brdId>', methods=('POST', 'GET'))
def post_write(brdId):
	print("post_write()")
	db =  DBUpdater()
	board_ls = db.load_board_list()
	# session의 'username'이 있으면 로그인
	if "username" in session: 	
		# 세션이 있는 경우
		# 특정 게시물 편집 html 불러오기
		board_ls = db.load_board_list()
		return render_template('pages/post.edit.html', board_ls=board_ls ,brdId=brdId)
	else:
		# 세션이 없는 경우'
		print('First Login')
		return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기! </a>"


# 편집 저장하기 버튼 클릭
@bp.route('/save/<int:pstId>/', methods=('GET', 'POST'))
def post_save_edit(pstId):
    brdId = request.form['brdId']
    db = DBUpdater()
    board_ls = db.load_board_list()
    print(request.form)
    db.update_post(request.form, pstId)
    return redirect(url_for('board_views.board_boardID', brdId=brdId, board_ls=board_ls))


# 작성 저장하기 버튼 클릭
@bp.route('/save/', methods=('GET', 'POST'))
def post_save_new():
	brdId = request.form['brdId']
	userId = session["username"]
	title = request.form['title']
	pstCntnt = request.form['pstCntnt']

	db = DBUpdater()
	db.insertPost(brdId, userId, title, pstCntnt)
	board_ls = db.load_board_list()

	return redirect(url_for('board_views.board_boardID', brdId=brdId, board_ls=board_ls))
    

# 작성 저장하기 버튼 클릭
@bp.route('/like/<pstId>/<type>/<post>', methods=('GET', 'POST'))
def like_unlike_click(pstId, type, post):
	"""
	Args:
		pstId (_type_): _description_
		type (_type_): like or unlike
		post (int, optional): _description_. Defaults to 1.
	"""
	post = int(post)
	pstId = int(pstId)
	print('like_unlike_click :', pstId, type, post)
	# try:
	if "username" in session:
		# 존재하면 로직 진행
		db = DBUpdater()
		# 해당 게시물에 대한 좋아요 싫어요 row가 있는지 확인
		if db.existence_item(pstId, session['username'], post) == 0:
			# 없으면 insert 기본 값
			db.insert_item(pstId, session['username'], post)

		# 해당 type(like or unlike)이 False 이면 : True로 변경
		# 해당 type이 True 이면 : False로 변경
		db.update_item_type(type, pstId, session['username'], post)

		# 해당 pstId의 sum(like) 값을 Post의 pstLikeCnt으로 업데이트
		id = db.update_pstlikeCnt(type, pstId, post)
		return redirect(url_for('post_views.post', pstId=id))
	else:
		# 세션이 없는 경우'
		print('First Login')
		return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기! </a>"

myproject/sesac/views/user_views.py
# myproject/sesac/views/user_views.py
from flask import Blueprint, render_template
from flask import Flask, url_for, request, session, redirect, app, make_response, flash, jsonify

from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from ..sqlModule import DBUpdater

bp = Blueprint('user_views', __name__, url_prefix='/user')
db = DBUpdater()
board_ls = db.load_board_list()

# User 회원가입 (/user/signup)
@bp.route('/signup', methods=('GET', 'POST'))
def user_signup():
    # pages/user.signup.html에서 method POST로 정보가 수신된 경우
    if(request.method == 'POST'):
        # form으로 받아온 정보 저장 
        result = request.form.to_dict()
        print(result)
        tel = result['tel']
        subNm = result['subNm']
        userId = result['userId']
        # 이미 존재하는 date인지 확인하기 위해 db에서 date 출력
        db = DBUpdater()
        
        newTel = db.extractWhere("tel", "UserInfo", "tel", tel)
        newSubNm = db.extractWhere("subNm", "UserInfo", "subNm", subNm)
        newUserId = db.extractWhere("userId", "UserInfo", "userId", userId)
        
        # 만약 기존에 있는 계정이라면 다시 signup page 반환
            # ! : 기존에 있었던 정보인지 user에게 알려줄 방법_ flash로
            
        if (tel==newTel):
            print("이미 존재하는 tel 입니다.")
            flash("이미 가입된 휴대전화 번호입니다.")
            return render_template('pages/user.signup.html', data="tel")
        
        elif(userId==newUserId) or (subNm==newSubNm):
            print("중복된 닉네임 또는 아이디이기 때문에 가입하실 수 없습니다.")
            flash("중복된 닉네임 또는 아이디이기 때문에 가입하실 수 없습니다.")
            return render_template('pages/user.signup.html', data="user")
        
        # 기존에 있는 정보가 아니라면 userInfo에 저장 후 login page 반환
            # ! : 회원가입이 완료됐음을 알려줄 방법_ ?
        else:
            # userPw는 generate_password_hash()로 암호화해서 저장
            db.insertUserInfo(result['userId'], generate_password_hash(result['userPw']), result['userNm'], result['subNm'] , result['tel'], result['email'])
            return render_template('pages/user.login.html')
    
    # pages/user.signup.html에서 method GET으로 정보가 수신된 경우
    else:
        # 다시 pages/user.signup.html 반환
        return render_template('pages/user.signup.html')
    
# fetch
@bp.route('/respones', methods=('GET', 'POST'))
def fetch():
    if request.method == 'POST':
        result = request.get_json()["subNm"]
        
        db = DBUpdater()
        newResult = db.extractWhere("subNm", "UserInfo", "subNm", result)
        
        if(result == newResult):
            return jsonify({'msg': '중복된 닉네임입니다'})
        else:
            return jsonify({'msg': '사용 가능한 닉네임입니다.'})
    else:
        return render_template('pages/user.signup.html')
    
# fetch2
@bp.route('/respones2', methods=('GET', 'POST'))
def fetch2():
    if request.method == 'POST':
        result = request.get_json()["userId"]
        
        db = DBUpdater()
        newResult = db.extractWhere("userId", "UserInfo", "userId", result)
        
        if(result == newResult):
            return jsonify({'msg': '중복된 아이디입니다'})
        else:
            return jsonify({'msg': '사용 가능한 아이디입니다.'})
    else:
        return render_template('pages/user.signup.html')
    

################################################################################################################################################

# 로그인 (/user/login)
@bp.route('/login', methods=('GET', 'POST'))
def user_login():
    
    # pages/user.login.html에서 method POST로 정보가 수신된 경우
    if(request.method == 'POST'):
        # form으로 받아온 정보 저장 
        result = request.form.to_dict()
        print(result["userId"], result["userPw"])
        
        # 수신된 정보 존재 확인 및 ID&PW 매칭
        db = DBUpdater()
        userPw = db.extractWhere("userPw", "UserInfo", "userId", result['userId'])
        userNm = db.extractWhere("userNm", "UserInfo", "userId", result['userId'])
        userSubNm = db.extractWhere("subNm", "UserInfo", "userId", result['userId'])
        grade = db.extractWhere("grade", "UserInfo", "userId", result['userId'])
        
            # 정보가 일치하는 경우 userId를 session에 저장 후 page/main.html 반환
        if(check_password_hash(userPw, result["userPw"])):  # check_password_hash()로 복호화해서 확인
            print("정보가 일치합니다. 로그인 성공 !")

            # 추후에 게시물 작성할 때 필요한 session 정보 저장
            session['userId'] = request.form['userId']
            session['userNm'] = userNm
            session['userSubNm'] = userSubNm
            session['username'] = request.form['userId']
            session['grade'] = grade
            
            print("User Session: ", session)
            return redirect(url_for('main', board_ls=board_ls))
        
            # 없는 정보거나 정보가 일치하지 않을 경우 다시 pages/user.login.html 반환
        else:
            print("정보가 일치하지 않습니다. 올바르게 입력해주세요")
            flash("정보가 일치하지 않습니다. 올바르게 입력해주세요")
            return render_template('pages/user.login.html')
        
    # pages/user.login.html에서 method GET으로 정보가 수신된 경우
    else:
        return render_template('pages/user.login.html')
    
################################################################################################################################################

# 로그아웃(/user/logout)
@bp.route('/logout')
def user_logout():
    
    # session에 userId가 존재하면 userId 제거
    if("userId" in session):
        session.clear()
        print(session) 
    # session에 userId가 존재하지 않으면 session 출력해 확인
    else:
        print(session) 
    # pages/main.html 반환
    return redirect(url_for('main'))

################################################################################################################################################

# 마이페이지(/user/mypage)
@bp.route('/mypage')
def user_mypage():    
    # data는 유저 아이디랑 일치하는 모든 게시물과 댓글
    # session에 userId가 있는 경우
    if 'userId' in session:
        db = DBUpdater()
        post_list = db.load_post_userId_list(session['userId'])
        comm_list = db.load_comm_userId_list(session['userId'])
        print(post_list)
        print("\n\n\n\n\n\n\n")
        print(comm_list)
        
        return render_template('pages/user.mypage.html', post_list=post_list, comm_list=comm_list, board_ls=board_ls)
    else:
        # session에 'userId'가 없으면 pages/user.login.html 반환
        return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기 </a>"
    
################################################################################################################################################

myproject/sesac/templates/pages/admin.boardinfo.html
{% extends '/layouts/base_updown.html' %} {% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/admin.css') }}"
/>

<section class = "page-upper">
  <h2 class = "page-title">게시판 관리</h2>
</section>


<div class="quickmenu">
  <ul class = "quicklist">
    <li class = "quickitem"><a href="{{url_for('admin_views.admin_userinfo')}}">유저 관리</a></li>
    <li class = "quickitem"><a href="{{url_for('admin_views.admin_boardinfo')}}">게시판 관리</a></li>
    <li class = "quickitem"><a href="{{url_for('admin_views.admin_postinfo')}}">게시물 관리</a></li>
    <li class = "quickitem"><a href="{{url_for('admin_views.admin_comminfo')}}">댓글 관리</a></li>
  </ul>
</div>


<div class="brdInfo">
  <div class="brdTable">
    {% if BoardInfo %}
    <div class="brdinner">
      <div class="inner-">ID</div>
      <div class="inner-">이름</div>
      <div class="inner-">쓸모없는거</div>
      <div class="inner-">삭제</div>
      <div class="inner-">이름 수정</div>
    </div>
    {% for board in BoardInfo %}
    <div class="brditems">
      {% for value in board.values() %}
      <div class="inner-">{{value}}</div>
      {% endfor %}
      <div class="inner-">
        <a href="{{url_for('admin_views.boardinfo_del', brdId=board.brdId)}}"
          >삭제</a
        >
      </div>
      <div class = "modify-bar">
        <form
        class = "modify-input"
          method="post"
          action="{{url_for('admin_views.boardinfo_edit', brdId=board.brdId)}}"
          style="display: flex"
        >
          <input name="brdNm" type="text" placeholder="{{board.brdNm}}" />
          <button type="submit">수정</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <li>BoardInfo가 없음</li>
    {% endif %}
  </div>
</div>
{% endblock %}

myproject/sesac/templates/pages/board.brdId.html
{% extends '/layouts/base_updown.html' %}{% block content %}
<section>
  <h2>board.brdId.html</h2>
  <p>all board</p>
  {{board_list}} 
  {% if board_list %} 
    {% for board in board_list %}
    <ul>
      {% for key, value in board.items() %}
        <li><a href="brdId={{ board.brdId }}/">{{key}} - {{value}}</a></li>
      {% endfor %}
    </ul>
    {% endfor %} 
  {% else %}
  <p>board_list가 없습니다.</p>
  
  {% endif %}
</section>
{% endblock %}

myproject/sesac/templates/pages/post.html
{% extends '/layouts/base_updown.html' %} {% block content %}

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css"
/>
<link rel="stylesheet" href="style.css" />
<link rel="stylesheet" href="style_menu.css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.min.js"></script>
<script type="text/javascript" defer src="main.js"></script>
<script type="text/javascript" defer src="menu.js"></script>

<script src="{{url_for('static',filename='js/post.js') }}"></script>


{% if board_ls %}
<div class="wrapper">
  <div class="overlay"></div>

  <div class="middle">
    <img class = "imgcontainer" src = "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FtP2nA%2FbtrULN6ZVHm%2FkNek9g9Pv9lunoCLcqYmQk%2Fimg.png"></div>
  </div>
  

  <div class="bodywrapper">
    <div class="board-bodywrapper">
      <aside class="sidebar">
        <div class="sidebar-title"><h3 class="sidebar-name">📋</h3></div>
        <ul class="sidebar-list">
          <li class="sidebar-item">
            <a href="{{url_for('board_views.board')}}">전체게시판</a>
          </li>
          {% if board_ls %} 
            {% for board in board_ls %}
            <li class="sidebar-item">
              <a
                href="{{url_for('board_views.board_boardID', brdId=board.brdId)}}"
                >{{board.brdNm}}</a
              >
            </li>
          {% endfor %} 
          {% endif %}
        </ul>
      </aside>

      <section class="main">
        <div class="articlecontainer">
          <div class="postcontainer">
            <div class="post-upper">
              {% if post_list %} 
              {% for post in post_list %}
                {% for board in board_ls %}
                  {% if board.brdId == post.brdId %}
                    <div class="post-position">{{board.brdNm}}</div>
                  {% endif %}
                {% endfor %}
              <div class="post-title-bar"><h2>{{post.title}}</h2></div>
              <div class="post-upper-name">{{userSN[0].subNm}}</div>

              <ul class="post-upper-list">
                <li class="post-upper-item">
                  <div class="post-upper-time">생성일: {{post.pstCrtDate.strftime('%Y-%m-%d')}}</div>
                  <div class="post-upper-view">조회수: {{post.vwCnt}}</div>
                </li>
                <li class="post-upper-item">
                  <div class="mod-btn">
                    <a href="{{url_for('post_views.post_edit', pstId=post.pstId)}}">수정</a>
                  </div>
                  <div class="del-btn">
                    <a href="{{url_for('post_views.post_del', pstId=post.pstId)}}">삭제</a>
                  </div>
                  {% for message in get_flashed_messages() %}
                    <script>
                      Swal.fire({
                        icon: 'error',
                        title: '경고',
                        text: `{{ message }}`,
                      });
                    </script>
                  {% endfor %}
                </li>
              </ul>
              {% endfor %}
            </div>

            <div class="post-article">{{post_list[0].pstCntnt}}</div>

            <div class="post-bottom-list">
            </div>

            <div class="post-comment-container">
              <a href="{{url_for('post_views.like_unlike_click', pstId=post_list[0].pstId, type='like', post=1)}}">좋아요 [ {{post_list[0].pstLikeCnt}} ]</a>
              <a href="{{url_for('post_views.like_unlike_click', pstId=post_list[0].pstId, type='unlike', post=1)}}">싫어요[ {{post_list[0].pstUnlikeCnt}} ]</a>
              <br><br>
              <div class="now-comment">댓글</div>

              <form
                method="post"
                action="{{url_for('comment_views.comment_add', pstId=post_list[0].pstId)}}"
                style="display: flex;"
              >
                <input
                    class="comment-input"
                    type="text"
                    name="cmtCntnt"
                    id="cmtCntnt"
                    placeholder="댓글을 입력해주세요"
                    onkeydown="enterFunc(event,'cmtCntnt','submit')"
                  />
                <input
                    class="submit-input"
                    type="submit"
                    id="submit"
                    value="추가하기"
                    onclick="btnClick(event)"
                  />
                </form>
              {% if comment_list %} 
              {% for comment in comment_list %}
              <div class="comment-view">
                <ul class="comment-view-list">
                  <li class="comment-view-item">
                    <div class="comment-user">{{ comment.subNm }}</div>
                    <div class="comment-content">{{ comment.cmtCntnt }}</div>
                    <div class="comment-time">{{ comment.cmtCrtDate.strftime('%Y-%m-%d')}}</div>
                    <div class="comment-btn">
                      <ul class="comment-btn-list">
                        <li class="comment-btn-item">
                          <a>{{ comment.cmtLikeCnt }}</a>
                          <a
                            href="{{url_for('post_views.like_unlike_click', pstId=comment.cmtId, type='like', post=0)}}"
                            >O</a
                          >
                        </li>
                        <li class="comment-btn-item">
                          <a>{{ comment.cmtUnlikeCnt }}</a>
                          <a
                            href="{{url_for('post_views.like_unlike_click', pstId=comment.cmtId, type='unlike', post=0)}}"
                            >X</a
                          >
                        </li>
                        <li class="comment-btn-item">
                          <a
                            href="{{url_for('comment_views.comment_del', cmtId=comment.cmtId)}}"
                            >삭제</a
                          >
                        </li>
                      </ul>
                    </div>
                  </li>
                </ul>
              </div>
              {% endfor %} {% else %}
              <li style="list-style: none;"></li>
              {% endif %}
            </div>

            <div class="post-article-under">
              <button type="button" class="backtomainBtn">
                <a
                  href="{{url_for('board_views.board_boardID', brdId=post_list[0].brdId)}}"
                >
                  목록으로 돌아가기</a
                >
              </button>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<script>
  $(window);
</script>

{% else %}
<p>post_list가 없습니다.</p>
{% endif %}
{% endif %}
{% endblock %}