myproject/sesac/views/board_views.py
# myproject/sesac/views/board_views.py
from flask import Flask, url_for, request, session, redirect, app
from flask import Blueprint, render_template
from ..sqlModule import DBUpdater
bp = Blueprint('board_views', __name__, url_prefix='/board')

# /board
@bp.route('/')
def board():
    print("board()")
    db = DBUpdater()
    
    number= 5
    page = request.args.get('page', type=int, default=1)
    paging = db.pageSelect2(number ,page)
    board_list = db.load_board_list()
    board_ls = db.load_board_list()
    post_list = db.load_post_list()
    post_len= len(post_list)
    post_len2={'count' : len(post_list)}
    ## 최대 페이지 = 전체 게시글수 -1 을 10으로 나눈 몫에 +1
    max_page = (post_len-1) // number +1
    boards={}
    boards['number']= number
    boards['page']= page
    boards['board_list'] = board_list
    boards['postCnt']= post_len2
    boards['post_list']= paging
    boards['max_page']= list(range(1, max_page+1))

    print(boards)
    # 전체 게시판 html 불러오기
    return render_template('pages/board.html', boards=boards, board_ls=board_ls)

# /board/boardId
@bp.route('/brdId=<int:brdId>/', methods=('GET', 'POST'))
def board_boardID(brdId):
    number= 5
    page = request.args.get('page', type=int, default=1)
    """
    Args:
        brdId (int): 게시판 ID
    """
    print('board_boardID(brdId) -', brdId,"\n")
    
    db = DBUpdater()
    # board_list = 전체 게시판 리스트
    board_list = db.load_board_list()
    # data = 특정 게시판의 게시물 리스트
    data = db.eachPageSelect2(number, page, brdId)
    ## 특정 게시판의 카운트수
    cntAll= db.pageCnt(brdId)
    max_page = (cntAll['count'] -1) // number +1
    boards={}
    boards['number']= number
    boards['page']= page
    boards['brdId']= brdId
    boards['board_list']= board_list
    boards['post_list'] = data
    boards['postCnt']= cntAll
    boards['max_page']= list(range(1, max_page+1))
    print('-'*20,boards)
    return render_template('pages/board.html', boards=boards, board_ls=board_list)

@bp.route('/comp/')
def compInfo():
    db = DBUpdater()
    board_ls = db.load_board_list()
    return render_template('pages/competition.html', board_ls=board_ls)

myproject/sesac/views/user_views.py
# myproject/sesac/views/user_views.py
from flask import Blueprint, render_template
from flask import Flask, url_for, request, session, redirect, app, make_response, flash, jsonify

from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from ..sqlModule import DBUpdater

bp = Blueprint('user_views', __name__, url_prefix='/user')
db = DBUpdater()
board_ls = db.load_board_list()

# User 회원가입 (/user/signup)
@bp.route('/signup', methods=('GET', 'POST'))
def user_signup():
    # pages/user.signup.html에서 method POST로 정보가 수신된 경우
    if(request.method == 'POST'):
        # form으로 받아온 정보 저장 
        result = request.form.to_dict()
        print(result)
        tel = result['tel']
        subNm = result['subNm']
        userId = result['userId']
        # 이미 존재하는 date인지 확인하기 위해 db에서 date 출력
        db = DBUpdater()
        
        newTel = db.extractWhere("tel", "UserInfo", "tel", tel)
        newSubNm = db.extractWhere("subNm", "UserInfo", "subNm", subNm)
        newUserId = db.extractWhere("userId", "UserInfo", "userId", userId)
        
        # 만약 기존에 있는 계정이라면 다시 signup page 반환
            # ! : 기존에 있었던 정보인지 user에게 알려줄 방법_ flash로
            
        if (tel==newTel):
            print("이미 존재하는 tel 입니다.")
            flash("이미 가입된 휴대전화 번호입니다.")
            return render_template('pages/user.signup.html', data="tel")
        
        elif(userId==newUserId) or (subNm==newSubNm):
            print("중복된 닉네임 또는 아이디이기 때문에 가입하실 수 없습니다.")
            flash("중복된 닉네임 또는 아이디이기 때문에 가입하실 수 없습니다.")
            return render_template('pages/user.signup.html', data="user")
        
        # 기존에 있는 정보가 아니라면 userInfo에 저장 후 login page 반환
            # ! : 회원가입이 완료됐음을 알려줄 방법_ ?
        else:
            # userPw는 generate_password_hash()로 암호화해서 저장
            db.insertUserInfo(result['userId'], generate_password_hash(result['userPw']), result['userNm'], result['subNm'] , result['tel'], result['email'])
            return render_template('pages/user.login.html')
    
    # pages/user.signup.html에서 method GET으로 정보가 수신된 경우
    else:
        # 다시 pages/user.signup.html 반환
        return render_template('pages/user.signup.html')
    
# fetch
@bp.route('/respones', methods=('GET', 'POST'))
def fetch():
    if request.method == 'POST':
        result = request.get_json()["subNm"]
        
        db = DBUpdater()
        newResult = db.extractWhere("subNm", "UserInfo", "subNm", result)
        
        if(result == newResult):
            return jsonify({'msg': '중복된 닉네임입니다'})
        else:
            return jsonify({'msg': '사용 가능한 닉네임입니다.'})
    else:
        return render_template('pages/user.signup.html')
    
# fetch2
@bp.route('/respones2', methods=('GET', 'POST'))
def fetch2():
    if request.method == 'POST':
        result = request.get_json()["userId"]
        
        db = DBUpdater()
        newResult = db.extractWhere("userId", "UserInfo", "userId", result)
        
        if(result == newResult):
            return jsonify({'msg': '중복된 아이디입니다'})
        else:
            return jsonify({'msg': '사용 가능한 아이디입니다.'})
    else:
        return render_template('pages/user.signup.html')
    

################################################################################################################################################

# 로그인 (/user/login)
@bp.route('/login', methods=('GET', 'POST'))
def user_login():
    
    # pages/user.login.html에서 method POST로 정보가 수신된 경우
    if(request.method == 'POST'):
        # form으로 받아온 정보 저장 
        result = request.form.to_dict()
        print(result["userId"], result["userPw"])
        
        # 수신된 정보 존재 확인 및 ID&PW 매칭
        db = DBUpdater()
        userPw = db.extractWhere("userPw", "UserInfo", "userId", result['userId'])
        userNm = db.extractWhere("userNm", "UserInfo", "userId", result['userId'])
        userSubNm = db.extractWhere("subNm", "UserInfo", "userId", result['userId'])
        grade = db.extractWhere("grade", "UserInfo", "userId", result['userId'])
        
            # 정보가 일치하는 경우 userId를 session에 저장 후 page/main.html 반환
        if(check_password_hash(userPw, result["userPw"])):  # check_password_hash()로 복호화해서 확인
            print("정보가 일치합니다. 로그인 성공 !")

            # 추후에 게시물 작성할 때 필요한 session 정보 저장
            session['userId'] = request.form['userId']
            session['userNm'] = userNm
            session['userSubNm'] = userSubNm
            session['username'] = request.form['userId']
            session['grade'] = grade
            
            print("User Session: ", session)
            return redirect(url_for('main', board_ls=board_ls))
        
            # 없는 정보거나 정보가 일치하지 않을 경우 다시 pages/user.login.html 반환
        else:
            print("정보가 일치하지 않습니다. 올바르게 입력해주세요")
            flash("정보가 일치하지 않습니다. 올바르게 입력해주세요")
            return render_template('pages/user.login.html')
        
    # pages/user.login.html에서 method GET으로 정보가 수신된 경우
    else:
        return render_template('pages/user.login.html')
    
################################################################################################################################################

# 로그아웃(/user/logout)
@bp.route('/logout')
def user_logout():
    
    # session에 userId가 존재하면 userId 제거
    if("userId" in session):
        session.clear()
        print(session) 
    # session에 userId가 존재하지 않으면 session 출력해 확인
    else:
        print(session) 
    # pages/main.html 반환
    return redirect(url_for('main'))

################################################################################################################################################

# 마이페이지(/user/mypage)
@bp.route('/mypage')
def user_mypage():    
    # data는 유저 아이디랑 일치하는 모든 게시물과 댓글
    # session에 userId가 있는 경우
    if 'userId' in session:
        db = DBUpdater()
        post_list = db.load_post_userId_list(session['userId'])
        comm_list = db.load_comm_userId_list(session['userId'])
        print(post_list)
        print("\n\n\n\n\n\n\n")
        print(comm_list)
        
        return render_template('pages/user.mypage.html', post_list=post_list, comm_list=comm_list, board_ls=board_ls)
    else:
        # session에 'userId'가 없으면 pages/user.login.html 반환
        return "로그인 해주세요. <br><a href = '/user/login'> 로그인 하러가기 </a>"
    
################################################################################################################################################

myproject/sesac/templates/layouts/base.html
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- pybo CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <title>Login</title>
  </head>
  <body>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
  </body>
</html>

myproject/sesac/templates/layouts/base_updown.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Sesac Community</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/layout.style.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/layout.style_menu.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.min.js"></script>
    <script
      type="text/javascript"
      defer
      src="{{ url_for('static', filename='js/main.js') }}"
    ></script>
    <script
      type="text/javascript"
      defer
      src="{{ url_for('static', filename='js/menu.js') }}"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <!-- 배너 관련 script-->
    <script defer src="{{ url_for('static', filename='js/app.js') }}"></script>
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>-->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>

    <!--배너 관련 script-->
  </head>

  <body>
    <div class="wrapper">
      <header class="menucontainer">
        <div class="loginbar">
          <ul class="loginbar-list">
            <a class="navbar-togglebtn" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
            <!-- 로그인바 아이템 내부 로그인 시 로그인/로그아웃, 회원가입/마이페이지로 변경되는 기능 구현해야 함 -->
            {% if session['username'] %}
            <li class="loginbar-item">
              <button
                class="btn-login"
                onclick="location.href='{{url_for('user_views.user_logout')}}'"
                type="button"
              >
                로그아웃
              </button>
            </li>
            <li class="loginbar-item">
              <button
                class="btn-login"
                onclick="location.href='{{url_for('user_views.user_mypage')}}'"
                type="button"
              >
                마이페이지
              </button>
            </li>

            {% else %}
            <li class="loginbar-item">
              <button
                class="btn-login"
                onclick="location.href='{{url_for('user_views.user_login')}}'"
                type="button"
              >
                로그인
              </button>
            </li>
            <li class="loginbar-item">
              <button
                class="btn-login"
                onclick="location.href='{{url_for('user_views.user_signup')}}'"
                type="button"
              >
                회원가입
              </button>
            </li>
            {% endif %}
          </ul>
        </div>
        <div class="menu">
          <ul class="menu-list">
            <li class="menu-item"><a href="{{url_for('main')}}"> 홈</a></li>
            <li class="menu-item">
              <div class="dropdown" style="margin: auto 0; text-align: center">
                <button
                  class="btn btn-secondary dropdown-toggle"
                  type="button"
                  data-toggle="dropdown"
                  id="dropdownBtn"
                  data-bs-auto-close="true"
                  aria-expanded="false"
                  style="
                    display: flex;
                    background-color: rgba(255, 255, 255, 0);
                    color: rgb(0, 0, 0);
                    border: 0px;
                    font-size: 20px;
                    margin: 0px;
                    padding: 0px;
                  "
                >
                  게시판
                </button>

                <div class="dropdown-menu">
                  <a
                  class="dropdown-item"
                  style="z-index: 101"
                  href="{{url_for('board_views.board')}}"
                  >전체게시판</a
                  >
                  {% for board in board_ls%}
                  <a
                    class="dropdown-item"
                    style="z-index: 101"
                    href="{{url_for('board_views.board_boardID', brdId=board.brdId)}}"
                    >{{board.brdNm}}</a
                  >
                  {% endfor %}
                </div>
              </div>
            </li>
            <li class="menu-item">
              <a href="https://sesac.seoul.kr/common/greeting.do">SeSAC</a>
            </li>
            {% if session['room'] %}
            <li class="menu-item">
              <a href="{{url_for('main.chat', tag=session['room'])}}">
                실시간</a
              >
            </li>
            {% else %}
            <li class="menu-item">
              <a href="{{url_for('main.chat', tag='All')}}"> 실시간 </a>
            </li>
            {% endif %}
            <li class="menu-item">
              <a href='{{url_for("board_views.compInfo")}}'> 공모전 </a>
            </li>
          </ul>
        </div>
      </header>

      <!-- 기본 템플릿 안에 삽입될 내용 Start -->
      {% block content %} {% endblock %}
      <!-- 기본 템플릿 안에 삽입될 내용 End -->   
    </div>
    <!-- <footer class="bottom">
      <a href ="https://github.com/Sbeom12/sesac_webproject"> <img class = "bottom-git" src = "https://seeklogo.com/images/G/github-logo-5F384D0265-seeklogo.com.png" style="width: 40px; height: 40px;"></a>
    
    
      <a href="#" class="btn_top"> <img class = "bottom-top" src = "https://ps.w.org/wpfront-scroll-top/assets/icon.svg?rev=1534312"> </a>
    </footer> -->
    <script>
      $(window);
    </script>
  </body>

</html>